In [1]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [3]:
data=datasets.load_boston()
input=data["data"]
output=data["target"]
input=pd.DataFrame(input)
output=pd.DataFrame(output)
#adding 1 to last column of input
number_of_features=len(input[0])
input["x (n+1)"]=1
#convert to numpy
input=np.array(input)
output=np.array(output)
print(input)
print(output)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 1.0000e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 1.0000e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 1.0000e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 1.0000e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 1.0000e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.0000e+00]]
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]
 [15. ]
 [18.9]
 [21.7]
 [20.4]
 [18.2]
 [19.9]
 [23.1]
 [17.5]
 [20.2]
 [18.2]
 [13.6]
 [19.6]
 [15.2]
 [14.5]
 [15.6]
 [13.9]
 [16.6]
 [14.8]
 [18.4]
 [21. ]
 [12.7]
 [14.5]
 [13.2]
 [13.1]
 [13.5]
 [18.9]
 [20. ]
 [21. ]
 [24.7]
 [30.8]
 [34.9]
 [26.6]
 [25.3]
 [24.7]
 [21.2]
 [19.3]
 [20. ]
 [16.6]
 [14.4]
 [19.4]
 [19.7]
 [20.5]
 [25. ]
 [23.4]
 [18.9]
 [35.4]
 [24.7]
 [31.6]
 [23.3]
 [19.6]
 [18.7]
 [16. ]
 [22.2]
 [25. ]
 [33. ]
 [23.5]
 [19.4]
 [22. ]
 [17.4]
 [20

In [4]:
y=output.reshape(-1,1)
Y=np.asmatrix(y)
X=np.asmatrix(input)
X_transpose=np.transpose(X)
print("Y : ",Y.shape)
print("X : ",X.shape)
print("X_transpose : ",X_transpose.shape)

Y :  (506, 1)
X :  (506, 14)
X_transpose :  (14, 506)


In [6]:
#so ab tak sab sahi
X_into_X_transpose_ka_inverse=np.linalg.inv(X*X_transpose)
coefficient_array=X_transpose*X_into_X_transpose_ka_inverse*Y
print(coefficient_array)

[[   55.79795786]
 [   31.50430069]
 [  140.18760808]
 [ -228.23631896]
 [-1206.38733796]
 [  565.73318007]
 [  322.6636443 ]
 [  -83.99444642]
 [  -49.16941326]
 [ 1256.69984777]
 [  186.65716617]
 [  476.55413906]
 [ -151.52763577]
 [-3667.09129426]]


In [8]:
code_se_coef_=[]
for i in range (len(coefficient_array)-1):
    code_se_coef_.append(coefficient_array[i][0])
print(code_se_coef_)

[matrix([[55.79795786]]), matrix([[31.50430069]]), matrix([[140.18760808]]), matrix([[-228.23631896]]), matrix([[-1206.38733796]]), matrix([[565.73318007]]), matrix([[322.6636443]]), matrix([[-83.99444642]]), matrix([[-49.16941326]]), matrix([[1256.69984777]]), matrix([[186.65716617]]), matrix([[476.55413906]]), matrix([[-151.52763577]])]


In [9]:
#so yeh matrix aayega
#change to list
coef_=coefficient_array.tolist()
print(coef_)

[[55.7979578565504], [31.504300689697157], [140.18760808210044], [-228.23631896078905], [-1206.38733795583], [565.7331800675602], [322.6636442999501], [-83.99444642178466], [-49.1694132566452], [1256.699847769738], [186.65716617107432], [476.55413906213397], [-151.52763576507573], [-3667.09129426479]]


In [10]:
code_se_coef_=[]
for i in range (len(coef_)-1):
    code_se_coef_.append(coef_[i][0])
print(code_se_coef_)

[55.7979578565504, 31.504300689697157, 140.18760808210044, -228.23631896078905, -1206.38733795583, 565.7331800675602, 322.6636442999501, -83.99444642178466, -49.1694132566452, 1256.699847769738, 186.65716617107432, 476.55413906213397, -151.52763576507573]


In [11]:
code_se_intercept_=coef_[len(coef_)-1][0]
print(code_se_intercept_)

-3667.09129426479
